Results:
  save_results: True
  save_dir: "results"
  use_wandb: True

DatasetConfig:
    HEIGHT:      256
    WIDTH:       256
    CHANNELS:    3
    NUM_CLASSES: 102
    MEAN:        [0.4344, 0.3768, 0.2862]
    STD:         [0.0870, 0.0593, 0.0716]
    DATA_ROOT:   "data_flowers"

TrainingConfig:
    # training 
    BATCH_SIZE:      32
    NUM_EPOCHS:      1
    LEARNING_RATE:   0.0003
    NUM_WORKERS:     0 
    DEVICE:          "DEVICE"
    CKPT_DIR:        "checkpoints_ldm"
    CKPT_NAME:       ""
    # difussion process
    BETA_START:      0.0001
    BETA_END:        0.02
    NUM_TIMESTEPS:   500
    T_EMB_DIM:       100
    PATCH_SIZE:      16 
    # transformer 
    CHANNELS:        500
    NUM_HEADS:       5 
    SEQUENCE_LENGTH: 256
    NUM_BLOCKS:      5